"""add_defect_table

Revision ID: 40b4b8762289
Revises: c0f74d4a30db
Create Date: 2026-02-19 20:59:41.227971

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40b4b8762289'
down_revision = 'c0f74d4a30db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('defect_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sub_module', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('fix_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('api_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['testexecution.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_project_id'), 'defects', ['project_id'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('scheduled_tasks', 'project_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'collection_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'test-suite'"))
    op.alter_column('scheduled_tasks', 'is_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('scheduled_tasks', 'notification_rule_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_foreign_key(None, 'scheduled_tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'scheduled_tasks', 'notification_rules', ['notification_rule_id'], ['id'])
    op.alter_column('task_execution_logs', 'task_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('task_execution_logs', 'execution_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('task_execution_logs', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('task_execution_logs', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_foreign_key(None, 'task_execution_logs', 'testexecution', ['execution_id'], ['id'])
    op.create_foreign_key(None, 'task_execution_logs', 'scheduled_tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_execution_logs', type_='foreignkey')
    op.drop_constraint(None, 'task_execution_logs', type_='foreignkey')
    op.alter_column('task_execution_logs', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('task_execution_logs', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('task_execution_logs', 'execution_id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('task_execution_logs', 'task_id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'scheduled_tasks', type_='foreignkey')
    op.drop_constraint(None, 'scheduled_tasks', type_='foreignkey')
    op.alter_column('scheduled_tasks', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('scheduled_tasks', 'notification_rule_id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('scheduled_tasks', 'is_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('scheduled_tasks', 'collection_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'test-suite'"))
    op.alter_column('scheduled_tasks', 'project_id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_defects_project_id'), table_name='defects')
    op.drop_table('defects')
    # ### end Alembic commands ###
