"""update_execution_table

Revision ID: 7881fb1235b0
Revises: e607011cbe80
Create Date: 2026-02-10 23:08:10.876387

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7881fb1235b0'
down_revision = 'e607011cbe80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executionrecord')
    op.add_column('testexecution', sa.Column('collection_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testexecution', 'collection_type')
    op.create_table('executionrecord',
    sa.Column('apifox_collection_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('total_cases', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passed_cases', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_cases', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_json', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('error_message', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('started_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
