"""add_notification_tables

Revision ID: e634d2aec366
Revises: 1439c35dd6d0
Create Date: 2026-02-17 19:35:50.822027

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e634d2aec366'
down_revision = '1439c35dd6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('channel_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_rules',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('trigger_config', sa.Text(), nullable=True),
    sa.Column('channel_ids', sa.Text(), nullable=False),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('channel_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['testexecution.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['notification_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_logs')
    op.drop_table('notification_rules')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
