/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutScheduledTasksRouteImport } from './routes/_layout/scheduled-tasks'
import { Route as LayoutReportsRouteImport } from './routes/_layout/reports'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutExecutionsRouteImport } from './routes/_layout/executions'
import { Route as LayoutDefectsRouteImport } from './routes/_layout/defects'
import { Route as LayoutAuditLogsRouteImport } from './routes/_layout/audit-logs'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects/$projectId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScheduledTasksRoute = LayoutScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsRoute = LayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExecutionsRoute = LayoutExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDefectsRoute = LayoutDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditLogsRoute = LayoutAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => LayoutProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/audit-logs': typeof LayoutAuditLogsRoute
  '/defects': typeof LayoutDefectsRoute
  '/executions': typeof LayoutExecutionsRoute
  '/items': typeof LayoutItemsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/reports': typeof LayoutReportsRoute
  '/scheduled-tasks': typeof LayoutScheduledTasksRoute
  '/settings': typeof LayoutSettingsRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/projects/': typeof LayoutProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/audit-logs': typeof LayoutAuditLogsRoute
  '/defects': typeof LayoutDefectsRoute
  '/executions': typeof LayoutExecutionsRoute
  '/items': typeof LayoutItemsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/reports': typeof LayoutReportsRoute
  '/scheduled-tasks': typeof LayoutScheduledTasksRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/projects': typeof LayoutProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/audit-logs': typeof LayoutAuditLogsRoute
  '/_layout/defects': typeof LayoutDefectsRoute
  '/_layout/executions': typeof LayoutExecutionsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/reports': typeof LayoutReportsRoute
  '/_layout/scheduled-tasks': typeof LayoutScheduledTasksRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/audit-logs'
    | '/defects'
    | '/executions'
    | '/items'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/scheduled-tasks'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/audit-logs'
    | '/defects'
    | '/executions'
    | '/items'
    | '/notifications'
    | '/reports'
    | '/scheduled-tasks'
    | '/settings'
    | '/'
    | '/projects/$projectId'
    | '/projects'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/audit-logs'
    | '/_layout/defects'
    | '/_layout/executions'
    | '/_layout/items'
    | '/_layout/notifications'
    | '/_layout/projects'
    | '/_layout/reports'
    | '/_layout/scheduled-tasks'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/projects/$projectId'
    | '/_layout/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scheduled-tasks': {
      id: '/_layout/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/scheduled-tasks'
      preLoaderRoute: typeof LayoutScheduledTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/executions': {
      id: '/_layout/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof LayoutExecutionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/defects': {
      id: '/_layout/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof LayoutDefectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit-logs': {
      id: '/_layout/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof LayoutAuditLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
  }
}

interface LayoutProjectsRouteChildren {
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAuditLogsRoute: typeof LayoutAuditLogsRoute
  LayoutDefectsRoute: typeof LayoutDefectsRoute
  LayoutExecutionsRoute: typeof LayoutExecutionsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutScheduledTasksRoute: typeof LayoutScheduledTasksRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAuditLogsRoute: LayoutAuditLogsRoute,
  LayoutDefectsRoute: LayoutDefectsRoute,
  LayoutExecutionsRoute: LayoutExecutionsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutScheduledTasksRoute: LayoutScheduledTasksRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
